import type { Config } from "tailwindcss";

// v8 -- bespoke per-lead homepages are real HTML generated by Gemini at
// runtime and stored in the database, not present in this repo's source
// files at build time -- Tailwind's normal content-scanning can't see
// those class names, so nothing would get generated for them without an
// explicit safelist. The color side is bounded and safe: the generation
// prompt forbids anything but the primary/neutral families, and
// enforceBrandColor() (src/lib/sanitize-generated-html.ts) deterministically
// rewrites any accent color that slips through anyway -- so only the real
// custom `primary`-derived classes (already covered by `theme.extend.colors`
// above) and neutral grayscale need safelisting here, plus the common
// structural utilities real page layouts actually use.
const NEUTRAL_FAMILIES = "slate|gray|zinc|neutral|stone";
const RESPONSIVE = ["", "sm:", "md:", "lg:", "xl:", "hover:", "focus:"];

export default {
  darkMode: ["class", "class"],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  safelist: [
    { pattern: new RegExp(`^(bg|text|border|from|via|to|ring|divide|decoration)-(${NEUTRAL_FAMILIES})-(50|100|200|300|400|500|600|700|800|900|950)$`), variants: RESPONSIVE },
    { pattern: /^(bg|text|border)-(white|black|transparent|current)(\/\d{1,3})?$/, variants: RESPONSIVE },
    { pattern: /^(flex|grid|hidden|block|inline|inline-block|inline-flex)$/, variants: RESPONSIVE },
    { pattern: /^(flex-row|flex-col|flex-wrap|flex-nowrap|items-(start|center|end|stretch)|justify-(start|center|end|between|around|evenly))$/, variants: RESPONSIVE },
    { pattern: /^grid-cols-(1|2|3|4|5|6|12)$/, variants: RESPONSIVE },
    { pattern: /^(gap|p|px|py|pt|pb|pl|pr|m|mx|my|mt|mb|ml|mr|space-x|space-y)-(0|0\.5|1|1\.5|2|2\.5|3|3\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32)$/, variants: RESPONSIVE },
    { pattern: /^(w|h|max-w|min-h)-(full|screen|auto|fit|\d+|\d+\/\d+)$/, variants: RESPONSIVE },
    { pattern: /^rounded(-(sm|md|lg|xl|2xl|3xl|full))?$/, variants: RESPONSIVE },
    { pattern: /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl)$/, variants: RESPONSIVE },
    { pattern: /^font-(thin|light|normal|medium|semibold|bold|extrabold|black)$/, variants: RESPONSIVE },
    { pattern: /^(leading|tracking)-(tight|snug|normal|relaxed|loose|wide|wider)$/, variants: RESPONSIVE },
    { pattern: /^(shadow|shadow-sm|shadow-md|shadow-xl|shadow-2xl|opacity-\d{1,3}|overflow-hidden|relative|absolute|sticky|top-0|z-10|z-20|z-50)$/, variants: RESPONSIVE },
  ],
  theme: {
  	extend: {
  		fontFamily: {
  			sans: [
  				'var(--font-sans)',
  				'ui-sans-serif',
  				'system-ui',
  				'sans-serif'
  			],
  			display: [
  				'var(--font-display)',
  				'var(--font-sans)',
  				'ui-sans-serif',
  				'sans-serif'
  			]
  		},
  		colors: {
  			border: 'hsl(var(--border))',
  			input: 'hsl(var(--input))',
  			ring: 'hsl(var(--ring))',
  			background: 'hsl(var(--background))',
  			foreground: 'hsl(var(--foreground))',
  			primary: {
  				DEFAULT: 'hsl(var(--primary))',
  				foreground: 'hsl(var(--primary-foreground))'
  			},
  			secondary: {
  				DEFAULT: 'hsl(var(--secondary))',
  				foreground: 'hsl(var(--secondary-foreground))'
  			},
  			muted: {
  				DEFAULT: 'hsl(var(--muted))',
  				foreground: 'hsl(var(--muted-foreground))'
  			},
  			accent: {
  				DEFAULT: 'hsl(var(--accent))',
  				foreground: 'hsl(var(--accent-foreground))'
  			},
  			card: {
  				DEFAULT: 'hsl(var(--card))',
  				foreground: 'hsl(var(--card-foreground))'
  			},
  			success: {
  				DEFAULT: 'hsl(var(--success))',
  				foreground: 'hsl(var(--success-foreground))'
  			},
  			warning: {
  				DEFAULT: 'hsl(var(--warning))',
  				foreground: 'hsl(var(--warning-foreground))'
  			},
  			danger: {
  				DEFAULT: 'hsl(var(--danger))',
  				foreground: 'hsl(var(--danger-foreground))'
  			},
  			sidebar: {
  				DEFAULT: 'hsl(var(--sidebar-background))',
  				foreground: 'hsl(var(--sidebar-foreground))',
  				primary: 'hsl(var(--sidebar-primary))',
  				'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
  				accent: 'hsl(var(--sidebar-accent))',
  				'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
  				border: 'hsl(var(--sidebar-border))',
  				ring: 'hsl(var(--sidebar-ring))'
  			}
  		},
  		boxShadow: {
  			card: '0 1px 2px 0 rgb(15 23 42 / 0.04), 0 1px 3px 0 rgb(15 23 42 / 0.06)',
  			popover: '0 4px 6px -1px rgb(15 23 42 / 0.08), 0 8px 24px -4px rgb(15 23 42 / 0.1)',
  			lift: 'var(--shadow-lift)',
  			glow: 'var(--shadow-glow)'
  		},
  		backgroundImage: {
  			'gradient-primary': 'linear-gradient(135deg, hsl(var(--primary-h) var(--primary-s) calc(var(--primary-l) + 8%)), hsl(var(--primary-h) var(--primary-s) calc(var(--primary-l) - 12%)))'
  		},
  		borderRadius: {
  			lg: 'var(--radius)',
  			md: 'calc(var(--radius) - 2px)',
  			sm: 'calc(var(--radius) - 4px)'
  		}
  	}
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
