import { ArrowRight, Check, Clock3, Code2, Globe2, MessageCircle, Search, Smartphone } from "lucide-react";
import { CrispChat } from "@/components/CrispChat";
import { Footer } from "@/components/landing/Footer";
import { RedesignIntakeFlow } from "@/components/landing/RedesignIntakeFlow";

const EXAMPLES = [
  ["applied-construction.jpg", "Applied Construction"],
  ["true-ventilation.jpg", "True Ventilation"],
  ["pinnacle-restoration.jpg", "Pinnacle Restoration"],
  ["canadian-home-style.jpg", "Canadian Home Style"],
  ["indoorclimatesolutionstn.jpg", "Indoor Climate Solutions"],
  ["advanced-egress-solutions.jpg", "Advanced Egress Solutions"],
] as const;

const FAQ = [
  ["Why is the homepage redesign free?", "We want you to judge the quality before deciding whether to hire us. The concept should be useful whether or not we work together."],
  ["What do I receive?", "A human-reviewed homepage mockup, desktop and mobile direction, a website audit, the problems we found, and a clear explanation of what should change."],
  ["Is this a template?", "No. We use your real business information, brand, services, images, and category references. The final concept still receives a human design review before delivery."],
  ["How long does it take?", "Our target is 48 hours after the request is accepted. Complicated sites or missing content may need more time, and we will tell you rather than send weak work."],
  ["What happens if I like it?", "We can talk through the next step if the direction feels right. There is no pressure to continue."],
  ["Will the site rank on Google or AI search?", "The paid build includes a sound technical, schema, content, and internal-linking foundation. No honest provider can guarantee rankings; ongoing authority and content work compound over time."],
];

export function FreeRedesignLanding() {
  return (
    <main className="bg-white text-[#161925]">
      <header className="absolute inset-x-0 top-0 z-30"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><a href="/" className="flex items-center gap-3 text-white"><img src="/icon.png" alt="BarakahSoft" className="h-9 w-9" /><span className="font-bold">BarakahSoft</span></a><nav className="hidden items-center gap-7 text-sm font-semibold text-white/70 md:flex"><a href="#examples">Examples</a><a href="#process">How it works</a><a href="#included">What you get</a><a href="#faq">FAQ</a></nav><a href="#top" className="rounded-lg bg-[#ef1550] px-4 py-2.5 text-sm font-bold text-white">Get my free redesign</a></div></header>

      <section id="top" className="relative overflow-hidden bg-[#171827] px-6 pb-24 pt-36 text-white"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(to_right,rgba(255,255,255,.05)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,.05)_1px,transparent_1px)] [background-size:48px_48px]" /><div className="absolute -right-24 top-20 h-80 w-80 rounded-full bg-[#ef1550]/15 blur-3xl" /><div className="relative mx-auto max-w-5xl text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#ff4778]">Free homepage redesign</p><h1 className="mx-auto mt-5 max-w-4xl font-sans text-5xl font-black uppercase leading-[.95] tracking-[-0.055em] sm:text-7xl">Get your homepage redesigned <span className="bg-[#ef1550] px-2 text-white">for free</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-white/65">See exactly how your homepage could look using your real business, branding, services, and images. No card. No obligation. Review the work before you spend anything.</p><RedesignIntakeFlow /><div className="mt-7 flex flex-wrap justify-center gap-x-6 gap-y-2 text-xs font-semibold text-white/55"><span>Human-reviewed concept</span><span>Mobile-first direction</span><span>Audit included</span></div></div></section>

      <section id="examples" className="px-6 py-24"><div className="mx-auto max-w-5xl text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#ef1550]">Real website work</p><h2 className="mt-3 font-sans text-4xl font-black uppercase tracking-[-0.04em] sm:text-5xl">See what a stronger first impression can look like.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-[#687083]">The design direction changes by business. We study the category, preserve what is real, and raise the production value instead of dropping every lead into one template.</p><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{EXAMPLES.map(([image, title]) => <article key={image} className="overflow-hidden border border-[#dfe3ea] bg-white text-left shadow-sm"><div className="h-52 overflow-hidden bg-[#f3f4f7]"><img src={`/refs/clients/${image}`} alt={title} className="h-full w-full object-cover object-top transition duration-500 hover:scale-105" /></div><div className="border-t border-[#eceef2] p-4"><p className="font-bold">{title}</p><p className="mt-1 text-xs text-[#7a8291]">Homepage design example</p></div></article>)}</div></div></section>

      <section className="bg-[#f5f6f8] px-6 py-20"><div className="mx-auto grid max-w-5xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#ef1550]">Mobile matters</p><h2 className="mt-3 font-sans text-4xl font-black uppercase tracking-[-0.04em]">The concept must work in your customer&apos;s hand.</h2><p className="mt-5 text-sm leading-6 text-[#687083]">A homepage is not approved because it looks good on a large monitor. Calls, quote requests, service navigation, and trust must remain obvious on mobile.</p></div><div className="grid grid-cols-3 gap-4">{EXAMPLES.slice(0, 3).map(([image, title]) => <div key={`mobile-${image}`} className="mx-auto h-80 w-full max-w-40 overflow-hidden rounded-[1.6rem] border-[6px] border-[#171827] bg-white shadow-xl"><img src={`/refs/clients/${image}`} alt={`${title} mobile preview`} className="h-full w-full object-cover object-top" /></div>)}</div></div></section>

      <section id="process" className="bg-[#171827] px-6 py-24 text-white"><div className="mx-auto max-w-5xl"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#ff4778]">How it works</p><h2 className="mt-3 font-sans text-4xl font-black uppercase tracking-[-0.04em] sm:text-5xl">From form to fresh homepage.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-white/55">Automation prepares the evidence. A person controls what you see.</p></div><div className="mx-auto mt-14 max-w-3xl space-y-4">{[[Globe2, "Share your current website", "Tell us what feels wrong and where customers struggle."], [Search, "We audit and benchmark", "We find evidenced issues and study the visual bar in your category."], [Code2, "We build the concept", "Your logo, colours, real facts, and best usable images shape the direction."], [MessageCircle, "You receive the preview", "Review the homepage and audit. Continue only if the direction is useful."]].map(([Icon, title, body], index) => <div key={title as string} className="grid gap-5 rounded-xl border border-white/10 bg-white/5 p-6 sm:grid-cols-[64px_1fr_auto] sm:items-center"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#ef1550] text-white"><Icon className="h-5 w-5" /></div><div><p className="text-lg font-bold">{title as string}</p><p className="mt-1 text-sm text-white/55">{body as string}</p></div><span className="text-xs font-bold text-white/35">0{index + 1}</span></div>)}</div></div></section>

      <section id="included" className="px-6 py-24"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#ef1550]">Everything in the free concept</p><h2 className="mt-3 font-sans text-4xl font-black uppercase tracking-[-0.04em]">Useful even if you never hire us.</h2><div className="mx-auto mt-10 max-w-2xl bg-[#171827] p-6 text-left text-white shadow-xl">{["Premium homepage mockup", "Desktop and mobile direction", "Evidence-based website audit", "Competitor and category benchmark", "What was wrong → what we changed", "A clear next-step recommendation"].map((item) => <p key={item} className="flex items-center gap-3 border-b border-white/10 py-4 text-sm font-semibold last:border-0"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#ef1550]"><Check className="h-3 w-3" /></span>{item}</p>)}</div></div></section>

      <section className="bg-[#f5f6f8] px-6 py-20"><div className="mx-auto max-w-4xl"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#ef1550]">The people behind it</p><h2 className="mt-3 font-sans text-4xl font-black uppercase tracking-[-0.04em]">Human judgment stays in the loop.</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2">{[["Shakil Ahmed", "Research, design direction, and final quality", "https://barakahsoft.com/wp-content/uploads/2026/07/Shak-Headshot-Medium.jpeg"], ["Jim Sabellico", "Communication and client support", "https://barakahsoft.com/wp-content/uploads/2026/07/Jim-Headshot-Medium.jpeg"]].map(([name, role, image]) => <article key={name} className="flex items-center gap-5 border border-[#dfe3ea] bg-white p-5"><img src={image} alt={name} className="h-20 w-20 rounded-full object-cover object-top" /><div><p className="font-bold">{name}</p><p className="mt-1 text-sm text-[#687083]">{role}</p></div></article>)}</div></div></section>

      <section id="faq" className="px-6 py-24"><div className="mx-auto max-w-4xl"><h2 className="font-sans text-4xl font-black uppercase tracking-[-0.04em]">Common questions</h2><div className="mt-10 divide-y divide-[#e2e5ea]">{FAQ.map(([question, answer]) => <details key={question} className="group py-5"><summary className="cursor-pointer list-none font-bold">{question}<span className="float-right text-[#ef1550]">+</span></summary><p className="mt-3 max-w-2xl text-sm leading-6 text-[#687083]">{answer}</p></details>)}</div></div></section>

      <section className="px-6 pb-24"><div className="mx-auto max-w-4xl bg-[#171827] px-6 py-16 text-center text-white"><h2 className="font-sans text-4xl font-black uppercase tracking-[-0.04em]">Ready to see a better homepage?</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-white/55">Send your current website. We&apos;ll review it before accepting the build.</p><a href="#top" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-[#ef1550] px-6 py-3 text-sm font-bold text-white">Get my free redesign <ArrowRight className="h-4 w-4" /></a></div></section>
      <Footer />
      <CrispChat />
    </main>
  );
}
