import Link from "next/link";
import { ArrowLeft, CheckCircle2, FileText, Globe2, MessageCircle, PackageCheck } from "lucide-react";
import { ClientPortalChrome } from "@/components/client/ClientPortalChrome";

const DATA = {
  leads: { title: "Project activity", intro: "The decisions and approvals connected to your website.", rows: [["Homepage concept", "Approved for full-site build", "Complete"], ["Issue-versus-fix report", "Ready to review", "Ready"], ["Sitemap", "38 generated · 4 to review", "Review"], ["Client message", "Your team is available", "Open"]] },
  reports: { title: "Your issue-versus-fix report", intro: "A plain-language explanation of what the current site needs and what the new build changes.", rows: [["Mobile hierarchy", "Clearer contact path", "Fixed"], ["Service discovery", "Service hub + dedicated pages", "Fixed"], ["Trust proof", "Verified experience and local proof", "Fixed"], ["Content depth", "Existing posts + 8-10 launch posts", "In progress"]] },
  website: { title: "Complete website review", intro: "Review the homepage, services, blog, sitemap, and generated routes before approval.", rows: [["Homepage", "Preview ready", "Open preview"], ["Service pages", "38 routes generated", "Review sitemap"], ["Blog", "6 approved · 2 drafts", "Review content"], ["Validation", "Links and build passing", "View checks"]] },
  account: { title: "Ownership and handoff", intro: "Your approved content, media, and website files remain attached to the website version.", rows: [["Website files", "Complete project prepared", "Download"], ["Version", "York Electrical v1", "View history"], ["Launch notes", "Included for handoff", "View notes"], ["Support", "Message BarakahSoft", "Open message"]] },
} as const;

export function ClientPortalSection({ section }: { section: keyof typeof DATA }) { const data = DATA[section]; return <ClientPortalChrome><main className="min-h-screen bg-[#f5f9fc] px-6 py-10 text-[#1e212b]"><div className="mx-auto max-w-5xl"><Link href="/client-portal-prototype" className="inline-flex items-center gap-2 text-sm font-semibold text-[#60778d]"><ArrowLeft className="h-4 w-4" /> Back to portal</Link><div className="mt-8 flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#0c68c8]">York Electrical · client portal</p><h1 className="mt-2 font-sans text-4xl font-semibold tracking-[-0.04em] text-[#07284d]">{data.title}</h1><p className="mt-2 text-sm text-[#60778d]">{data.intro}</p></div><span className="hidden items-center gap-2 rounded-full bg-[#eaf8f0] px-3 py-1.5 text-xs font-bold text-[#167044] sm:flex"><CheckCircle2 className="h-3.5 w-3.5" /> Version protected</span></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{[[FileText, "Evidence", "Source attached"], [Globe2, "Website", "Preview ready"], [PackageCheck, "Handoff", "Export prepared"]].map(([Icon, title, body]) => <div key={title as string} className="rounded-2xl border border-[#d9e8f4] bg-white p-5 shadow-[0_8px_24px_rgba(7,40,77,0.04)]"><Icon className="h-5 w-5 text-[#0c68c8]" /><p className="mt-5 text-sm font-bold text-[#07284d]">{title as string}</p><p className="mt-1 text-xs text-[#7890a5]">{body as string}</p></div>)}</div><section className="mt-8 overflow-hidden rounded-2xl border border-[#d9e8f4] bg-white shadow-[0_8px_24px_rgba(7,40,77,0.04)]"><div className="border-b border-[#d9e8f4] p-5"><p className="text-lg font-bold text-[#07284d]">{data.title}</p><p className="mt-1 text-xs text-[#7890a5]">You can review, approve, or request a change. Nothing is silently overwritten.</p></div><div className="divide-y divide-[#e8f0f6]">{data.rows.map(([name, detail, action]) => <div key={name} className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#eef7ff] text-[#0c68c8]"><CheckCircle2 className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-[#07284d]">{name}</p><p className="mt-1 text-xs text-[#7890a5]">{detail}</p></div></div><button className="inline-flex items-center gap-2 rounded-lg border border-[#c8ddec] bg-white px-3 py-2 text-xs font-bold text-[#07284d]"><MessageCircle className="h-3.5 w-3.5" />{action}</button></div>)}</div></section></div></main></ClientPortalChrome>; }
