import Link from "next/link";
import { ArrowLeft, BarChart3, CheckCircle2, ExternalLink, FileSignature, Globe2, MessageCircle, PhoneCall } from "lucide-react";

const SECTIONS = {
  leads: { title: "Your opportunities", intro: "Every form inquiry and tracked call in one simple list.", rows: [["Roof replacement", "Form inquiry", "New"], ["Storm damage inspection", "Tracked call", "Contacted"], ["Commercial roof repair", "Form inquiry", "Qualified"], ["Gutter installation", "Form inquiry", "New"]] },
  reports: { title: "Your weekly report", intro: "A plain-language view of spend, inquiries, calls, and opportunities.", rows: [["Ad spend", "$412", "Paid directly to Meta"], ["Form inquiries", "14", "Validated submissions"], ["Tracked calls", "4", "Phone opportunities"], ["Qualified opportunities", "18 / 30", "Current campaign KPI"]] },
  website: { title: "Your website", intro: "Review the page and campaign assets built for your business.", rows: [["Preview", "Live", "Open website"], ["Services", "6 pages", "Review sitemap"], ["Service areas", "12 locations", "Review coverage"], ["SEO", "Connected", "View details"]] },
  account: { title: "Account and agreement", intro: "Your ownership, billing, agreement, and support details.", rows: [["Management", "$500/week", "No per-lead fees"], ["Ad budget", "Your account", "Paid directly to Meta"], ["Agreement", "Active", "View terms"], ["Support", "Crisp chat", "Message team"]] },
} as const;

export function ClientPortalSection({ section }: { section: keyof typeof SECTIONS }) {
  const data = SECTIONS[section];
  return <main className="min-h-screen bg-[#f5f9fc] px-6 py-10 text-[#1e212b]"><div className="mx-auto max-w-5xl"><Link href="/client-portal-prototype" className="inline-flex items-center gap-2 text-sm font-semibold text-[#60778d] hover:text-[#075da8]"><ArrowLeft className="h-4 w-4" /> Back to portal</Link><div className="mt-8 flex items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#0c68c8]">John Roofing · client portal</p><h1 className="mt-2 font-sans text-4xl font-semibold tracking-[-0.04em] text-[#07284d]">{data.title}</h1><p className="mt-2 text-sm text-[#60778d]">{data.intro}</p></div><span className="hidden items-center gap-2 rounded-full bg-[#eaf8f0] px-3 py-1.5 text-xs font-bold text-[#167044] sm:flex"><CheckCircle2 className="h-3.5 w-3.5" /> Connected</span></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{[[BarChart3, "Campaign", "Active"], [PhoneCall, "Calls", "Tracked separately"], [FileSignature, "Agreement", "On file"]].map(([Icon, title, body]) => <div key={title as string} className="rounded-2xl border border-[#d9e8f4] bg-white p-5 shadow-[0_8px_24px_rgba(7,40,77,0.04)]"><Icon className="h-5 w-5 text-[#0c68c8]" /><p className="mt-5 text-sm font-bold text-[#07284d]">{title as string}</p><p className="mt-1 text-xs text-[#7890a5]">{body as string}</p></div>)}</div><section className="mt-8 overflow-hidden rounded-2xl border border-[#d9e8f4] bg-white shadow-[0_8px_24px_rgba(7,40,77,0.04)]"><div className="border-b border-[#d9e8f4] p-5"><p className="text-lg font-bold text-[#07284d]">{data.title}</p><p className="mt-1 text-xs text-[#7890a5]">Your team sees the same business results. Internal notes and contracts remain private.</p></div><div className="divide-y divide-[#e8f0f6]">{data.rows.map(([name, detail, action]) => <div key={name} className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#eef7ff] text-[#0c68c8]"><Globe2 className="h-4 w-4" /></div><div><p className="text-sm font-bold text-[#07284d]">{name}</p><p className="mt-1 text-xs text-[#7890a5]">{detail}</p></div></div><span className="inline-flex items-center gap-1 text-xs font-bold text-[#075da8]">{action} <ExternalLink className="h-3 w-3" /></span></div>)}</div></section><div className="mt-8 flex items-center justify-between gap-4 rounded-2xl border border-[#c8ddec] bg-[#eef7ff] p-5"><div><p className="font-bold text-[#07284d]">Need help?</p><p className="mt-1 text-sm text-[#60778d]">Message your BarakahSoft team through Crisp.</p></div><span className="inline-flex items-center gap-2 rounded-lg bg-[#ffd12d] px-4 py-2.5 text-sm font-bold text-[#111]"><MessageCircle className="h-4 w-4" /> Message team</span></div></div></main>;
}
