"use client";

import { ArrowRight, Check, CircleDollarSign, Clock3, Mail, MessageCircle, Target } from "lucide-react";

const stages = [["New", 12], ["Research", 4], ["Report", 3], ["Talk", 4], ["Paid", 4]];

export function MinimalAdminHome({ setView }: { setView: (view: "Overview" | "Lead workspace" | "Reports" | "Communications" | "Delivery" | "Settings") => void }) {
  return <div className="space-y-7"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#533afd]">Owner home</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.05em] text-[#0d1738]">Today</h1></div><button onClick={() => setView("Lead workspace")} className="inline-flex items-center gap-2 rounded-md bg-[#533afd] px-4 py-2.5 text-sm font-bold text-white"><Target className="h-4 w-4" />Open lead</button></div>
    <section className="grid gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div className="rounded-lg border border-[#e5e2ff] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#533afd]">Do now</p><h2 className="mt-3 text-3xl font-semibold text-[#0d1738]">Send York&apos;s report</h2></div><Mail className="h-6 w-6 text-[#533afd]" /></div><p className="mt-3 text-sm text-[#42506a]">Report ready · Homepage ready</p><div className="mt-8 flex items-center gap-1">{stages.map(([label, value], index) => <div key={label as string} className="flex flex-1 items-center"><div className={`h-3 w-3 rounded-full ${index < 3 ? "bg-[#533afd]" : index === 3 ? "bg-[#ffe0ef] ring-2 ring-[#533afd]" : "bg-[#d6e3ff]"}`} /><div className={`h-1 flex-1 ${index < stages.length - 1 ? index < 2 ? "bg-[#533afd]" : "bg-[#d6e3ff]" : "hidden"}`} /></div>)}</div><div className="mt-2 flex justify-between text-[11px] text-[#777588]">{stages.map(([label]) => <span key={label as string}>{label}</span>)}</div><div className="mt-7 flex gap-3"><button onClick={() => setView("Reports")} className="inline-flex items-center gap-2 rounded-md bg-[#533afd] px-4 py-2.5 text-sm font-bold text-white">Open report <ArrowRight className="h-4 w-4" /></button><button onClick={() => setView("Communications")} className="inline-flex items-center gap-2 rounded-md border border-[#c8c4da] px-4 py-2.5 text-sm font-bold text-[#0d1738]"><MessageCircle className="h-4 w-4" />Talk</button></div></div><div className="rounded-lg border border-[#e5e2ff] bg-[#f0f3ff] p-6"><CircleDollarSign className="h-6 w-6 text-[#533afd]" /><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-[#777588]">Cash</p><p className="mt-2 text-4xl font-semibold text-[#0d1738]">$3,188</p><p className="mt-2 text-sm text-[#42506a]">4 paid websites</p><div className="mt-6 h-2 rounded-full bg-white"><div className="h-2 w-2/3 rounded-full bg-[#533afd]" /></div><p className="mt-2 text-xs text-[#777588]">$5,400 blocked</p></div></section>
    <section className="rounded-lg border border-[#e5e2ff] bg-white"><div className="flex items-center justify-between border-b border-[#e5e2ff] p-5"><div><p className="text-lg font-bold text-[#0d1738]">Up next</p><p className="mt-1 text-xs text-[#777588]">Open one. Do one thing.</p></div><Clock3 className="h-5 w-5 text-[#533afd]" /></div><div className="divide-y divide-[#eef0f7]">{[["York Electrical", "Send report", "Now"], ["John Roofing", "Reply", "Today"], ["Brightline Plumbing", "Confirm payment", "Tomorrow"]].map(([name, action, due]) => <button key={name} onClick={() => setView("Lead workspace")} className="flex w-full items-center justify-between gap-4 p-5 text-left hover:bg-[#f9f9ff]"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#e3dfff] font-bold text-[#533afd]">{name[0]}</span><div><p className="text-sm font-bold text-[#0d1738]">{name}</p><p className="mt-1 text-xs text-[#777588]">{action}</p></div></div><span className={`text-xs font-bold ${due === "Now" ? "text-[#533afd]" : "text-[#777588]"}`}>{due}</span></button>)}</div></section>
    <div className="flex items-center gap-2 text-xs text-[#777588]"><Check className="h-4 w-4 text-[#0b8f5b]" />No lead without a next action.</div></div>;
}
