"use client";

import { ArrowRight, Check, CheckCircle2, Eye, FileText, MapPin, MessageCircle, Search, Sparkles, Target, Users } from "lucide-react";

const MAP = Array.from({ length: 49 }, (_, index) => index);
const SIGNALS = [
  ["SEO foundation", "29", "10 important fixes", "#ff6b6b", Search],
  ["Local visibility", "10/49", "You appear today", "#ffb84d", MapPin],
  ["Trust signals", "3", "Proof gaps found", "#8b7cff", Users],
];

export function PremiumClientReport({ setTab }: { setTab: (tab: string) => void }) {
  return <div className="space-y-8">
    <section className="premium-report-hero relative overflow-hidden rounded-[28px] bg-[#07284d] p-7 text-white shadow-[0_24px_70px_rgba(7,40,77,0.2)] lg:p-10">
      <div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-[#ffd12d]/15 blur-3xl" />
      <div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-end">
        <div className="max-w-2xl"><div className="flex items-center gap-3"><span className="rounded-full bg-[#ffd12d] px-3 py-1 text-[11px] font-bold uppercase tracking-[0.16em] text-[#111]">Your redesign report</span><span className="text-xs text-white/55">York Electrical</span></div><h1 className="mt-5 max-w-xl text-4xl font-semibold leading-[1.05] tracking-[-0.05em] sm:text-6xl">The gap is clear. The next step is yours.</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/70">We studied your business, market, website, and competitors, then built a better direction around what is already true about your company.</p></div>
        <div className="flex shrink-0 flex-col gap-3 sm:flex-row lg:flex-col"><button onClick={() => setTab("Website")} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#ffd12d] px-5 py-3 text-sm font-bold text-[#111]">See the new homepage <ArrowRight className="h-4 w-4" /></button><button onClick={() => setTab("Conversation")} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/25 px-5 py-3 text-sm font-bold text-white"><MessageCircle className="h-4 w-4" />Ask the team</button></div>
      </div>
      <div className="relative mt-10 grid gap-2 sm:grid-cols-5">{[["01", "Received", "Done"], ["02", "Researched", "Done"], ["03", "Redesigned", "Done"], ["04", "Reviewed", "Now"], ["05", "Launch", "Next"]].map(([number, title, state], index) => <div key={title} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold ${index < 3 ? "bg-[#5ad0a8] text-[#07284d]" : index === 3 ? "bg-[#ffd12d] text-[#07284d]" : "bg-white/10 text-white/70"}`}>{index < 3 ? <Check className="h-4 w-4" /> : number}</span><div><p className="text-xs font-bold">{title}</p><p className="mt-0.5 text-[10px] text-white/50">{state}</p></div></div>)}</div>
    </section>

    <section className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]">
      <div className="rounded-2xl border border-[#d9e8f4] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#0c68c8]">What changed</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-[#07284d]">From hard to understand to easy to trust.</h2></div><Sparkles className="h-6 w-6 text-[#ffd12d]" /></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-[#ffd8d8] bg-[#fff8f8] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#b42318]">Before</p><div className="mt-4 rounded-lg bg-white p-3 shadow-sm"><div className="flex gap-1"><i className="h-1.5 w-12 rounded-full bg-[#dfe5eb]" /><i className="h-1.5 w-5 rounded-full bg-[#dfe5eb]" /></div><div className="mt-4 h-16 rounded bg-[#eef1f4]" /><div className="mt-3 grid grid-cols-3 gap-1"><i className="h-7 rounded bg-[#eef1f4]" /><i className="h-7 rounded bg-[#eef1f4]" /><i className="h-7 rounded bg-[#eef1f4]" /></div></div><p className="mt-3 text-xs leading-5 text-[#60778d]">Services and proof were hidden in the page.</p></div><div className="rounded-xl border border-[#c8ead8] bg-[#f5fcf7] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#167044]">After</p><div className="mt-4 rounded-lg bg-white p-3 shadow-[0_8px_18px_rgba(22,112,68,0.1)]"><div className="flex items-center justify-between"><i className="h-1.5 w-14 rounded-full bg-[#07284d]" /><b className="rounded bg-[#ffd12d] px-2 py-1 text-[8px] text-[#111]">CALL NOW</b></div><div className="mt-4 h-16 rounded bg-gradient-to-br from-[#dcefff] to-[#f5fcf7]" /><div className="mt-3 grid grid-cols-3 gap-1"><i className="h-7 rounded bg-[#eef7ff]" /><i className="h-7 rounded bg-[#fff8d9]" /><i className="h-7 rounded bg-[#eef7ff]" /></div></div><p className="mt-3 text-xs leading-5 text-[#60778d]">The right proof and next step lead the page.</p></div></div></div>
      <div className="rounded-2xl border border-[#d9e8f4] bg-[#fafaff] p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#0c68c8]">The opportunity</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-[#07284d]">Your business is stronger than the current first impression.</h2><div className="mt-6 space-y-5">{SIGNALS.map(([label, value, detail, color, Icon]) => <div key={label as string} className="flex items-center gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white shadow-sm"><Icon className="h-5 w-5" style={{ color: color as string }} /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold text-[#07284d]">{label as string}</span><strong className="text-xl text-[#07284d]">{value as string}</strong></div><div className="mt-2 h-2 rounded-full bg-[#e7eaf0]"><div className="h-2 rounded-full" style={{ width: `${label === "SEO foundation" ? 42 : label === "Local visibility" ? 20 : 38}%`, backgroundColor: color as string }} /></div><p className="mt-1 text-[11px] text-[#7890a5]">{detail as string}</p></div></div>)}</div></div>
    </section>

    <section className="rounded-2xl border border-[#d9e8f4] bg-white p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#0c68c8]">Local visibility</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-[#07284d]">Where customers search, you are missing the conversation.</h2></div><p className="max-w-sm text-right text-xs leading-5 text-[#7890a5]">49 local checkpoints across Queens. Each square is one search area.</p></div><div className="mt-7 grid gap-7 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div className="rounded-2xl bg-[#07284d] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#ffd12d]">The picture today</p><p className="mt-4 text-6xl font-semibold tracking-[-0.06em]">10<span className="text-2xl text-white/50">/49</span></p><p className="mt-2 text-sm text-white/65">checkpoints where your business appeared</p><div className="mt-6 flex items-center gap-3 text-xs"><span className="h-3 w-3 rounded-full bg-[#5ad0a8]" />Visible <span className="ml-3 h-3 w-3 rounded-full bg-[#ff6b6b]" />Missing</div></div><div><div className="grid grid-cols-7 gap-2 sm:gap-3">{MAP.map((cell) => <div key={cell} className={`aspect-square rounded-md transition hover:scale-110 ${cell % 7 === 0 ? "bg-[#ff6b6b]" : cell % 5 === 0 ? "bg-[#ffdca8]" : "bg-[#e8e4ff]"}`} title={`Search area ${cell + 1}`} />)}</div><div className="mt-4 flex justify-between text-xs text-[#7890a5]"><span>More visible</span><span>Less visible</span></div></div></div></section>

    <section className="grid gap-5 md:grid-cols-3">{[["What we found", "Services, trust proof, mobile hierarchy, and local visibility gaps.", FileText], ["What we built", "A homepage and complete website direction around the real business.", Eye], ["What happens next", "Review the work, ask questions, and approve the next step.", Target]].map(([title, detail, Icon]) => <div key={title as string} className="rounded-2xl border border-[#d9e8f4] bg-white p-6"><Icon className="h-6 w-6 text-[#0c68c8]" /><h3 className="mt-6 text-lg font-bold text-[#07284d]">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#60778d]">{detail as string}</p></div>)}</section>

    <section className="flex flex-col justify-between gap-5 rounded-2xl bg-[#fff8d9] p-6 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#8c6800]">Your decision</p><h2 className="mt-2 text-2xl font-semibold text-[#07284d]">You can see the problem and the solution.</h2><p className="mt-2 text-sm text-[#60778d]">No pressure. Review the new homepage, ask us anything, or continue when it feels right.</p></div><div className="flex flex-wrap gap-3"><button onClick={() => setTab("Website")} className="inline-flex items-center gap-2 rounded-xl bg-[#ffd12d] px-5 py-3 text-sm font-bold text-[#111]">Review the build <ArrowRight className="h-4 w-4" /></button><button onClick={() => setTab("Conversation")} className="inline-flex items-center gap-2 rounded-xl border border-[#c8ddec] bg-white px-5 py-3 text-sm font-bold text-[#07284d]"><MessageCircle className="h-4 w-4" />Ask a question</button></div></section>
  </div>;
}
