"use client";

import { ArrowRight, Check, CircleDollarSign, Clock3, Mail, MessageCircle, Sparkles, Target } from "lucide-react";

const STAGES = [["New", 12, "#e8e4ff"], ["Research", 4, "#d9e9ff"], ["Report ready", 3, "#fff0c7"], ["Conversation", 4, "#ffe0ef"], ["Paid", 4, "#d9f5e8"]];

export function PremiumAdminHome({ setView }: { setView: (view: "Overview" | "Lead workspace" | "Reports" | "Communications" | "Delivery") => void }) {
  return <div className="space-y-8">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#8c6800]">Owner workspace</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.05em] text-[#07284d]">Today.</h1><p className="mt-2 text-sm text-[#7890a5]">The next action that moves a lead closer to money.</p></div><button onClick={() => setView("Lead workspace")} className="inline-flex items-center gap-2 rounded-md bg-[#ffd12d] px-4 py-2.5 text-sm font-bold text-[#111]"><Target className="h-4 w-4" />Open active lead</button></div>
    <section className="grid gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div className="rounded-2xl bg-[#07284d] p-7 text-white"><div className="flex items-center gap-3"><span className="rounded-full bg-[#ffd12d] px-3 py-1 text-[11px] font-bold uppercase tracking-[0.16em] text-[#111]">Do this now</span><span className="text-xs text-white/50">York Electrical · Facebook ad</span></div><h2 className="mt-5 text-3xl font-semibold tracking-[-0.04em]">Send the master report.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/65">The map grid, SEO audit, competitors, issue fixes, and new homepage are ready. This is the conversation opener.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={() => setView("Reports")} className="inline-flex items-center gap-2 rounded-md bg-[#ffd12d] px-4 py-2.5 text-sm font-bold text-[#111]"><Mail className="h-4 w-4" />Open report</button><button onClick={() => setView("Communications")} className="inline-flex items-center gap-2 rounded-md border border-white/25 px-4 py-2.5 text-sm font-bold text-white"><MessageCircle className="h-4 w-4" />Open conversation</button></div></div><div className="rounded-2xl border border-[#e5e2ff] bg-white p-6"><CircleDollarSign className="h-6 w-6 text-[#8c6800]" /><p className="mt-6 text-xs font-bold uppercase tracking-[0.16em] text-[#7890a5]">Cash position</p><p className="mt-2 text-4xl font-semibold text-[#07284d]">$3,188</p><p className="mt-2 text-sm text-[#7890a5]">4 paid website projects</p><div className="mt-6 h-2 rounded-full bg-[#f1f0f8]"><div className="h-2 w-2/3 rounded-full bg-[#ffd12d]" /></div><p className="mt-3 text-xs text-[#7890a5]">Goal: collect before production begins.</p></div></section>
    <section className="rounded-2xl border border-[#e5e2ff] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-lg font-bold text-[#07284d]">Lead journey</p><p className="mt-1 text-xs text-[#7890a5]">Every stage has one job.</p></div><span className="text-xs font-semibold text-[#7890a5]">27 active leads</span></div><div className="mt-7 grid gap-2 md:grid-cols-5">{STAGES.map(([label, value, color], index) => <div key={label as string} className="relative"><div className="flex h-28 flex-col justify-between rounded-lg p-4" style={{ backgroundColor: color as string }}><span className="text-xs font-bold uppercase tracking-wider text-[#42506a]">{label as string}</span><strong className="text-4xl font-semibold text-[#07284d]">{value as number}</strong></div>{index < STAGES.length - 1 && <ArrowRight className="absolute -right-3 top-12 z-10 hidden h-5 w-5 text-[#a7a4b6] md:block" />}</div>)}</div></section>
    <section className="grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded-2xl border border-[#e5e2ff] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-lg font-bold text-[#07284d]">Money path</p><p className="mt-1 text-xs text-[#7890a5]">What the business can become.</p></div><Sparkles className="h-5 w-5 text-[#8c6800]" /></div><div className="mt-6 space-y-4">{[["Free report", "Earn trust", "Sent"], ["Website", "$797", "4 ready"], ["Management", "Recurring", "2 interested"], ["Launch", "Client-owned", "Next"]].map(([label, value, state]) => <div key={label} className="flex items-center gap-4"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#fff8d9] text-sm font-bold text-[#8c6800]">✓</div><div className="flex-1"><p className="text-sm font-bold text-[#07284d]">{label}</p><p className="text-xs text-[#7890a5]">{state}</p></div><strong className="text-sm text-[#07284d]">{value}</strong></div>)}</div></div><div className="rounded-2xl border border-[#e5e2ff] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-lg font-bold text-[#07284d]">Next actions</p><p className="mt-1 text-xs text-[#7890a5]">Open one and keep moving.</p></div><Clock3 className="h-5 w-5 text-[#8c6800]" /></div><div className="mt-5 space-y-3">{[["York Electrical", "Send report", "Today"], ["John Roofing", "Reply to question", "Today"], ["Brightline Plumbing", "Confirm payment", "Tomorrow"]].map(([name, action, due]) => <button key={name} onClick={() => setView("Lead workspace")} className="flex w-full items-center justify-between rounded-lg border border-[#eef0f5] p-4 text-left hover:border-[#ffd12d]"><div><p className="text-sm font-bold text-[#07284d]">{name}</p><p className="mt-1 text-xs text-[#7890a5]">{action}</p></div><span className="text-xs font-bold text-[#8c6800]">{due}</span></button>)}</div></div></section>
  </div>;
}
